package nodomain.freeyourgadget.gadgetbridge.devices.pebble;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class IconConst {
    private static final Logger LOG = LoggerFactory.getLogger(IconConst.class);

    public static final byte NOTIFICATION_GENERIC = 1;
    public static final byte TIMELINE_MISSED_CALL = 2;
    public static final byte NOTIFICATION_REMINDER = 3;
    public static final byte NOTIFICATION_FLAG = 4;
    public static final byte NOTIFICATION_WHATSAPP = 5;
    public static final byte NOTIFICATION_TWITTER = 6;
    public static final byte NOTIFICATION_TELEGRAM = 7;
    public static final byte NOTIFICATION_GOOGLE_HANGOUTS = 8;
    public static final byte NOTIFICATION_GMAIL = 9;
    public static final byte NOTIFICATION_FACEBOOK_MESSENGER = 10;
    public static final byte NOTIFICATION_FACEBOOK = 11;
    public static final byte AUDIO_CASSETTE = 12;
    public static final byte ALARM_CLOCK = 13;
    public static final byte TIMELINE_WEATHER = 14;
    public static final byte TIMELINE_SUN = 16;
    public static final byte TIMELINE_SPORTS = 17;
    public static final byte GENERIC_EMAIL = 19;
    public static final byte AMERICAN_FOOTBALL = 20;
    public static final byte TIMELINE_CALENDAR = 21;
    public static final byte TIMELINE_BASEBALL = 22;
    public static final byte BIRTHDAY_EVENT = 23;
    public static final byte CAR_RENTAL = 24;
    public static final byte CLOUDY_DAY = 25;
    public static final byte CRICKET_GAME = 26;
    public static final byte DINNER_RESERVATION = 27;
    public static final byte GENERIC_WARNING = 28;
    public static final byte GLUCOSE_MONITOR = 29;
    public static final byte HOCKEY_GAME = 30;
    public static final byte HOTEL_RESERVATION = 31;
    public static final byte LIGHT_RAIN = 32;
    public static final byte LIGHT_SNOW = 33;
    public static final byte MOVIE_EVENT = 34;
    public static final byte MUSIC_EVENT = 35;
    public static final byte NEWS_EVENT = 36;
    public static final byte PARTLY_CLOUDY = 37;
    public static final byte PAY_BILL = 38;
    public static final byte RADIO_SHOW = 39;
    public static final byte SCHEDULED_EVENT = 40;
    public static final byte SOCCER_GAME = 41;
    public static final byte STOCKS_EVENT = 42;
    public static final byte RESULT_DELETED = 43;
    public static final byte CHECK_INTERNET_CONNECTION = 44;
    public static final byte GENERIC_SMS = 45;
    public static final byte RESULT_MUTE = 46;
    public static final byte RESULT_SENT = 47;
    public static final byte WATCH_DISCONNECTED = 48;
    public static final byte DURING_PHONE_CALL = 49;
    public static final byte TIDE_IS_HIGH = 50;
    public static final byte RESULT_DISMISSED = 51;
    public static final byte HEAVY_RAIN = 52;
    public static final byte HEAVY_SNOW = 53;
    public static final byte SCHEDULED_FLIGHT = 54;
    public static final byte GENERIC_CONFIRMATION = 55;
    public static final byte DAY_SEPARATOR = 56;
    public static final byte NO_EVENTS = 57;
    public static final byte NOTIFICATION_BLACKBERRY_MESSENGER = 58;
    public static final byte NOTIFICATION_INSTAGRAM = 59;
    public static final byte NOTIFICATION_MAILBOX = 60;
    public static final byte NOTIFICATION_GOOGLE_INBOX = 61;
    public static final byte RESULT_FAILED = 62;
    public static final byte GENERIC_QUESTION = 63;
    public static final byte NOTIFICATION_OUTLOOK = 64;
    public static final byte RAINING_AND_SNOWING = 65;
    public static final byte REACHED_FITNESS_GOAL = 66;
    public static final byte NOTIFICATION_LINE = 67;
    public static final byte NOTIFICATION_SKYPE = 68;
    public static final byte NOTIFICATION_SNAPCHAT = 69;
    public static final byte NOTIFICATION_VIBER = 70;
    public static final byte NOTIFICATION_WECHAT = 71;
    public static final byte NOTIFICATION_YAHOO_MAIL = 72;
    public static final byte TV_SHOW = 73;
    public static final byte BASKETBALL = 74;
    public static final byte DISMISSED_PHONE_CALL = 75;
    public static final byte NOTIFICATION_GOOGLE_MESSENGER = 76;
    public static final byte NOTIFICATION_HIPCHAT = 77;
    public static final byte INCOMING_PHONE_CALL = 78;
    public static final byte NOTIFICATION_KAKAOTALK = 79;
    public static final byte NOTIFICATION_KIK = 80;
    public static final byte NOTIFICATION_LIGHTHOUSE = 81;
    public static final byte LOCATION = 82;
    public static final byte SETTINGS = 83;
    public static final byte SUNRISE = 84;
    public static final byte SUNSET = 85;
    public static final byte FACETIME_DISMISSED = 86;
    public static final byte FACETIME_INCOMING = 87;
    public static final byte FACETIME_OUTGOING = 88;
    public static final byte FACETIME_MISSED = 89;
    public static final byte FACETIME_DURING = 90;
    public static final byte BLUESCREEN_OF_DEATH = 91;
    public static final byte START_MUSIC_PHONE = 92;

}

