language: android

jdk:
  - oraclejdk8
# disabled -- we now set sourceCompatibility and targetCompatibility appropriately
#  - oraclejdk7

env:
  - GRADLE_OPTS="-XX:MaxPermSize=256m"

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew build connectedCheck --stacktrace
  - bash config/travis/validate_fastlane_metadata.sh
